server:
  port: 8090

spring:
  redis: 
    host: redis_rate_limiter
    port: 6380
    timeout: 20000  
  
  cache:
    type: redis 

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # Timeout di connessione (5 secondi)
        response-timeout: 660s   # Timeout di risposta (11 minuti)
        wiretap: true  # Abilita log dettagliati delle richieste
        pool:
          type: fixed
          max-connections: 30  # Numero massimo di connessioni simultanee
          acquire-timeout: 5000  # Tempo massimo di attesa per una connessione libera
      routes:
        - id: fallback-route
          uri: http://localhost:8080/fallback # Dove si gestisce il fallback
          predicates:
            - Path=/fallback
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /${segment}
            - name: RedisCacheFilter
              args:
                ttl: 60
                cachePrefix: "test_cache:"
                methods: "GET, POST, PUT"
        - id: aggregated-route
          uri: no://op  //il gateway non inoltra direttamente la richiesta a un backend
          predicates:
            - Path=/aggregated
          filters:
            - name: Aggregation
              args:
                services: "http://httpbin.org/get, http://httpbin.org/bytes/10"
        - id: gamerepo-route
          uri: http://t4-controller:8084
          predicates:
            - Path=/gamerepo/**
          filters:
            - RewritePath=/gamerepo/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
            - name: RedisCacheFilter
              args:
                ttl: 60
                cachePrefix: "gamerepo_cache:"
                methods: "GET"
        - id: T7-route
          uri: http://t7-controller:8087
          predicates:
            - Path=/compile/jacoco/**
          filters:
            - RewritePath=/compile/jacoco/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
        - id: T8-route
          uri: http://t8-controller:8088
          predicates:
            - Path=/compile/evosuite/**
          filters:
            - RewritePath=/compile/evosuite/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 15
                redis-rate-limiter.requestedTokens: 1
        - id: T1-route
          uri: http://t1-controller:8081
          predicates:
            - Path=/adminService/**
          filters:
            - RewritePath=/adminService/(?<segment>.*), /${segment}
        - id: T23-route
          uri: http://t23-controller:8082
          predicates:
            - Path=/userService/**
          filters:
            - RewritePath=/userService/(?<segment>.*), /${segment}
        - id: T5-route
          uri: http://t5-controller:8085
          predicates:
            - Path=/gameEngine/**
          filters:
            - RewritePath=/gameEngine/(?<segment>.*), /${segment}

# Configurazioni aggiuntive per il logging e altre personalizzazioni
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.server: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    env:
      enabled: true
      show-values: ALWAYS

  metrics:
    tags:
      application: apiGateway
