name: t5

services:
  redis:
    image: redis:latest
    container_name: t5-redis
    restart: always
    expose:
      - "6379"
    networks:
      - global-network
  app:
    image: mick0974/a13:t5-g2
    container_name: t5-controller
    restart: always
    ports:
      - "8085:8085"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - global-network
    volumes:
      - VolumeT0:/VolumeT0

networks:
  global-network:
    external: true

volumes:
  VolumeT0:
    external: true