name: t1

services:
  controller:
    image: mick0974/a13:t1-g11
    container_name: t1-controller
    restart: always
    expose:
      - 8081
    environment:
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - mongo_db
    volumes:
      - ./FilesUpload:/Files-Upload
      - VolumeT0:/VolumeT0
    networks:
      - global-network

  mongo_db:
    image: "mongo:6.0.6"
    container_name: t1-mongo_db
    restart: always
    expose:
      - "27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_volume:/data/db
    networks:
      - global-network

networks:
  global-network:
    external: true

volumes:
  VolumeT0:
    external: true
  mongodb_data_volume: