name: t4

volumes:
  pgdata:
  appdata:
  pglogs:

services:
  db:
    image: postgres:14-alpine3.17
    container_name: t4-postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    command: >
      postgres -c logging_collector=off
               -c log_statement=all
               -c log_connections=on
               -c log_disconnections=on
               -c log_error_verbosity=verbose
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U t4_service -d t4_database'" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - global-network
    restart: always

  app:
    image: mick0974/a13:t4-g18
    container_name: t4-controller
    expose:
      - 8084
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
    depends_on:
      db:
        condition: service_healthy # parte solo se il db Ã¨ attivo
    networks:
      - global-network

networks:
  global-network:
    external: true